package thinking.in.java.code15;

public enum Watercolors {

	ZINC, LEMON_YELLOW, HEDIUM_YELLOW, DEEP_YELLOW, ORANGE,
	BRILLIANT_RED, CRIMSON, MAGENTA, ROSE_MADDER, VIOLEFT,
	CERULEAN_BLUE_HUE, PHTHALO_BLUE, ULTRAMARINE,
	COBALT_BLUE_HUE, PERMANENT_GREEN, VIRIDIAN_HUE,
	SAP_GREEN, YELLOW_OCHER, BURNT_SIENNA, RAW_UMBER,
	BURNT_UMBER, PAYNES_GRAY, IVORY_BLACK
}
